### PR TITLE
Added SVG Sprite Support

### PR DESCRIPTION
**Pull request by sarsamurmu**
At First, Run `npm i`. Then run `npm install -g grunt-cli`. 
Done! Now When You Build New SVGs Simply Run `npm run generate-sprite` or `grunt generate-sprite` to Generate SVG Sprite.
Though, I added `npm run generate-sprite` to `npm run build`. 
Hope it helps. Good Luck With That! :D

### CODE REVIEW

**Comment by tarunmangukiya** [comment]
Thanks for it! Is it possible to use `npm` directly, rather than `grunt`?

@antonreshetov What do you say?

**Comment by sarsamurmu** [comment]
No, I tried to find pure npm package but only found this grunt package.

**Comment by tarunmangukiya** [comment]
How about this one?
https://github.com/svgstore/svgstore

**Comment by sarsamurmu** [comment]
Yeah! This is Fine. Just opening Another PR.

**Pull request closed without merging**
