### PR TITLE
#167 Update outdated webpack package

### LINKED ISSUE #167: Update webpack dependencies
Outdated webpack using vulnerable `chokidar@2`.

I believe this will not affect much on your source, but will immensely help those using this awesome package.

Minimal change.

```bash
$ npm install
```

Before fix:

image

After fix:

image

### PR DESCRIPTION
**Pull request by Xavier-IV**
Closes #167 

Following conventional commit: https://www.conventionalcommits.org/en/v1.0.0/

### CODE REVIEW

**Comment by regazzoj** [comment]
Great ! Can anyone review this PR ? (:
It will be very to fix vulnerabilities from the package.

Thanks for your work @Xavier-IV !

**Comment by mluk-sastrify** [comment]
We are also waiting for this fix! :)

**Comment by regazzoj** [comment]
> Hi folks, Bumping up a Major version of SVGO requires some syntax changes. We will update these versions with the required file changes.

Okay ! Can I help in any way for this ? (:

**Comment by mluk-sastrify** [comment]
Hi!
Any action around this one? Any way we can help?

**Comment by imzedi** [comment]
- Upgrading webpack is included in latest release 💯
ref PR: https://github.com/Iconscout/unicons/pull/224

- Upgrading SVGO will taken in next release

So closing this PR

**Pull request closed without merging**
