### PR TITLE
Added Flipping Icons Feature

### PR DESCRIPTION
**Pull request by sarsamurmu**
Added Feature to Flip Icons as You want.
Add `flip-horizontal` or `flip-h` or `flip-x` to Flip Icon Horizontally.
Add `flip-vertical` or `flip-v` or `flip-y` to Flip Icon Vertically.

### CODE REVIEW

**Comment by tarunmangukiya** [comment]
Hey, I think it's difficult to edit `unicons.css` directly, as it's being generated dynamically with each release. We might need to create and manage separate file for it.

**Comment by sarsamurmu** [comment]
Make an another File named `utils.css` then use `@import "utils.css"` in unicons.css

**Comment by sarsamurmu** [comment]
You can use appendFile method in node fs for appending `@import "utils.css"` to `unicons.css` whenever new Version of CSS gets generated.

**Comment by tarunmangukiya** [comment]
@sarsamurmu This looks good. Can you add this codes to `before.css` as this fill be injected in `unicons.css` while build time. Also, how about adding rotate feature like FontAwesome?

**Comment by sarsamurmu** [comment]
Done. See #26.

**Pull request closed without merging**
